### ISSUE TITLE
WebWallet Conformance: Coinbase

### ISSUE THREAD

**Issue by okalouti** [omisego/web-wallet#52]

**Comment by nicholasmueller** [comment]
investigation result:
- mobile layout messed up
- unable to sign any transaction due to missing function

first issue, mobile confirm bit blocked, needs fix to ui
![coinbase-wallet-mobile](https://user-images.githubusercontent.com/29919550/81654613-e0a5fd00-945f-11ea-96b0-adc090a2ce3e.PNG)

what transaction signing looks like
![coinbase-wallet-sign](https://user-images.githubusercontent.com/29919550/81654625-e3a0ed80-945f-11ea-85f2-78d568216371.PNG)

unable to sign transaction due to missing function
![coinbase-wallet-signfail](https://user-images.githubusercontent.com/29919550/81654631-e4d21a80-945f-11ea-9553-e3f817ff73d9.PNG)

**Comment by nicholasmueller** [comment]
Signing works with my fixes in this [branch](https://github.com/omisego/web-wallet/tree/nm-imToken-fix) 

It was indeed due to the provider not implementing eip712 signing. User will sign a random blob instead of a nicely formatted typed data object 🤷🏻‍♂️.

Noting for reference, will close issue when branch noted is merged.
